### ISSUE TITLE
Remove the span if possible.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-internal-notes#4]
Is this necessary? I feel like you anchor tag can get the class.

https://github.com/coreymckrill/wporg-internal-notes/blob/946d4a8594a5372d80033953940613360525618a/src/notes-list/notes-list-item.js#L115

**Comment by coreymckrill** [comment]
Fair. I think when I built it I wasn't sure if every author would have a link, but now I can't think of a scenario where it wouldn't be there. Removed in 17fa710988cdafd5dd4fa20b328e39413f1ecad3
